services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_PORT=5173
      - VITE_HOST=0.0.0.0
      - FAST_REFRESH=true
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
